source 'https://rubygems.org'

gem 'kaminari'
gem 'geocoder'
gem 'rmagick'
gem 'carrierwave'
gem "cancan"
gem 'gdata-c2dm'
gem 'bookable', '~> 0.0.52'
gem 'devise'
gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

